
server:
  port: 8282
  servlet.context-path: /order

logging.level:
  root: DEBUG
  com.bestaone: DEBUG

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  username: root
  password: root

spring.session.store-type: none

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bestaone.himall.order.domain

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  autoRuntimeDialect: true
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  returnPageInfo: true
  params: count=countSql

spring.jackson:
  default-property-inclusion: non_null
  serialization.write-dates-as-timestamps: true

himall.monitor.enable: true
